### ISSUE TITLE
Implement commit history traversal

### ISSUE THREAD

**Issue by jordan-dimov** [a115/iCODES#1]
Currently, the tool only analyses and summarises the latest commit for a repo. 

Modify the `inspect_repo()` function to traverse the entire commit history of the specified branch, rather than just analysing the last commit.

This will likely involve iterating through the commits in the branch using GitPython and calling `extract_commit_info()` and `analyse_commit()` for each commit.

We should probably LIMIT this to a given number of commits to go back - supplied via a command-line option, and with a sensible fairly low default value (e.g. let's just start with 10). 

Commits should be processed in chronological order. I.e. start with Commit -10, then Commit -9, etc., until the last / newest Commit 0. It may be a good idea to provide the Summary (not the full Analysis) of each commit processed so far to the LLM when asking for the next analysis - for historical context.

**Comment by Bayo19** [comment]
I've made a PR for this issue

**Comment by jordan-dimov** [comment]
Implemented in #9
