### ISSUE TITLE
Implement a web-based UI using FastAPI

### ISSUE THREAD

**Issue by jordan-dimov** [a115/iCODES#6]
Develop a basic web-based user interface using FastAPI to provide an alternative to the CLI for searching and exploring commit data.

Create endpoints in the FastAPI application to handle search requests and return the results in JSON format.

**Comment by jordan-dimov** [comment]
I would also use Jinja 2 to render an HTML and Bootstrap CSS user interface to the tool.

**Comment by Zoom30** [comment]
This PR shall cover the first steps of creating a UI implementation: https://github.com/a115/icodes-ui/pull/1
